name: CI/CD Pipeline for Aircraft Maintenance Prediction

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: |
          python training.py

      - name: Run Prediction Script (with sample data)
        run: |
          echo "Running prediction script for testing"
          python prediction.py

      - name: Upload Models to Artifact Store
        uses: actions/upload-artifact@v3
        with:
          name: trained-models
          path: |
            models/maintenance_classifier_model.pkl
            models/remaining_life_regressor_model.pkl

      - name: Deploy to MLflow Tracking Server
        run: |
          echo "Logging models and metrics to MLflow"
          python mlflow_utils/mlflow_logging.py
